### ISSUE TITLE
Possible improvement

### ISSUE THREAD

**Issue by andreasdc** [2lstudios-mc/FlameCord#159]
I noticed some space for improvement during the attack in this part.
![image](https://user-images.githubusercontent.com/82218780/189679150-850f28d0-a392-49e7-b37c-cdc5aa7eb404.png)

**Comment by linsaftw** [comment]
I need to check this. The best solution would be to limit Login Request packets, but I think they are limited already. More than that cannot be done.

**Comment by andreasdc** [comment]
Isn't it better to not throw IndexOutOfBoundsException to save cpu?

**Comment by linsaftw** [comment]
> Isn't it better to not throw IndexOutOfBoundsException to save cpu?

It won't improve anything of this. The usage is because too many boolean bytes are being read for each Login packet of each connection.

**Comment by linsaftw** [comment]
![image](https://user-images.githubusercontent.com/25271111/189731647-447b7aea-d882-4272-8071-f28079649b7c.png)

This might be the culprit.

**Comment by linsaftw** [comment]
Fixed in [c985c47](https://github.com/2lstudios-mc/FlameCord/commit/c985c4727d4055d3174b13054d57c3c596db5ba1)

**Comment by andreasdc** [comment]
It still appears to throw IndexOutOfBoundsException
![image](https://user-images.githubusercontent.com/82218780/189894496-1a07fbee-3dee-496d-8f45-f897196025e7.png)

**Comment by linsaftw** [comment]
> It still appears to throw IndexOutOfBoundsException ![image](https://user-images.githubusercontent.com/82218780/189894496-1a07fbee-3dee-496d-8f45-f897196025e7.png)

I understand. Give me a minute.

**Comment by linsaftw** [comment]
Fixed on [0ef875f](https://github.com/2lstudios-mc/FlameCord/commit/0ef875f66b7d6f2db65eb92ba9c7e5316c9fbeca)! Sorry and please try again.

**Comment by andreasdc** [comment]
It doesn't seem to be thrown, good job and don't sorry! ❤️
