### ISSUE TITLE
1.17 client cannot join 1.19 server with ViaBackwards on 1.3.8

### ISSUE THREAD

**Issue by nhanledev** [2lstudios-mc/FlameCord#205]
Flamecord bug version: 1.3.8

Hello,

I test the new version and notice that 1.17 client randomly cannot connect to server that has ViaBackwards 4.6.0.
On Flamecord version 1.3.7 this still works normally.

Log:
```
[16:13:36 ERROR]: [/127.0.0.1:54854] <-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during initial handler process!
0d0a0d0a000d0a515549540a2000
[16:13:38 ERROR]: [/127.0.0.1:54864] <-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during initial handler process!
0d0a0d0a000d0a515549540a2000
[16:13:40 ERROR]: [/127.0.0.1:25764] <-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during initial handler process!
0d0a0d0a000d0a515549540a2000
[16:13:42 ERROR]: [/127.0.0.1:25778] <-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during initial handler process!
0d0a0d0a000d0a515549540a2000
```

**Comment by andreasdc** [comment]
I have the same error.

**Comment by linsaftw** [comment]
It was fixed on latest

**Comment by andreasdc** [comment]
It is not fixed and it appears that ViaVersion is the cause.

**Comment by linsaftw** [comment]
> It is not fixed and it appears that ViaVersion is the cause.

Make sure ViaVersion is updated and running in all spigot servers.

**Comment by Mercenarioo** [comment]
I have this error on my server too, I tried reporting it to ViaVersion, but apparently I got blocked for that. 
https://github.com/ViaVersion/ViaVersion/issues/3255
![image](https://user-images.githubusercontent.com/107449914/225666147-7617c834-8768-4a5a-84a8-1ef931f5b664.png)

**Comment by linsaftw** [comment]
Does this happen on normal BungeeCord too?

**Comment by Mercenarioo** [comment]
I don't know, but it's a problem with ViaVerison, older version with newest FlameCord works.

**Comment by nhanledev** [comment]
Hello, please use latest Flamecord 1.3.9 and ViaVersion, ViaBackwards (4.6.1). Everything works fine on my side, this issue is no longer an issue.

**Comment by Mercenarioo** [comment]
VV causes some incompabilities with plugins, I see possible fix for that.
